window.CMS_DATA_FALLBACK = {
  "Scholarships": [
    {
      "id": 1,
      "title": "HEC Need-Based Scholarship 2025",
      "description": "Higher Education Commission offers need-based scholarships for deserving students enrolled in HEC recognized universities across Pakistan.",
      "country": "Pakistan",
      "type": "Government",
      "funding": "Fully Funded",
      "deadline": "2025-06-30",
      "posted_date": "2025-04-10",
      "apply_link": "https://hec.gov.pk/scholarships",
      "tags": "HEC, Need-based, Undergraduate, Masters",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Islamabad",
      "level": "Undergraduate / Masters",
      "host_organization": "HEC Pakistan"
    },
    {
      "id": 2,
      "title": "British Council IELTS Award 2025",
      "description": "British Council offers scholarships for Pakistani students to pursue higher education in the United Kingdom. Covers tuition, living, and travel.",
      "country": "UK",
      "type": "International",
      "funding": "Fully Funded",
      "deadline": "2025-07-15",
      "posted_date": "2025-04-08",
      "apply_link": "https://www.britishcouncil.pk/scholarships",
      "tags": "UK, Fully Funded, Masters, British Council",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Online",
      "level": "Masters / PhD",
      "host_organization": "British Council"
    },
    {
      "id": 3,
      "title": "Chevening Scholarship 2025-26",
      "description": "UK government's global scholarship programme. Awards one-year master's degrees at leading UK universities to outstanding emerging leaders.",
      "country": "UK",
      "type": "International",
      "funding": "Fully Funded",
      "deadline": "2025-11-05",
      "posted_date": "2025-04-07",
      "apply_link": "https://www.chevening.org/apply/",
      "tags": "Chevening, UK, Masters, Leadership",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "United Kingdom",
      "level": "Masters",
      "host_organization": "UK Government / FCO"
    },
    {
      "id": 4,
      "title": "DAAD Scholarship Germany 2025",
      "description": "German Academic Exchange Service offers scholarships for Pakistani graduates to study in Germany. Covers full tuition and monthly stipend.",
      "country": "Germany",
      "type": "International",
      "funding": "Fully Funded",
      "deadline": "2025-08-20",
      "posted_date": "2025-04-05",
      "apply_link": "https://www.daad.de/en/",
      "tags": "DAAD, Germany, Masters, PhD, Europe",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Germany",
      "level": "Masters / PhD",
      "host_organization": "DAAD Germany"
    },
    {
      "id": 5,
      "title": "USAID Merit & Needs Scholarship",
      "description": "USAID Pakistan offers merit-cum-need based scholarships for undergraduate students from less developed areas of Pakistan.",
      "country": "Pakistan",
      "type": "Government",
      "funding": "Partial",
      "deadline": "2025-05-31",
      "posted_date": "2025-04-06",
      "apply_link": "https://usaid.gov/pakistan",
      "tags": "USAID, Pakistan, Undergraduate, Merit",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Lahore / Karachi",
      "level": "Undergraduate",
      "host_organization": "USAID Pakistan"
    },
    {
      "id": 6,
      "title": "Turkish Government Scholarship (Türkiye Burslari)",
      "description": "Full scholarship for international students to study in Turkey. Includes tuition, accommodation, monthly stipend and health insurance.",
      "country": "Turkey",
      "type": "International",
      "funding": "Fully Funded",
      "deadline": "2025-02-20",
      "posted_date": "2025-04-01",
      "apply_link": "https://www.turkiyeburslari.gov.tr/",
      "tags": "Turkey, Turkiye Burslari, Masters, Bachelors",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Turkey",
      "level": "Undergraduate / Masters / PhD",
      "host_organization": "Government of Turkey"
    },
    {
      "id": 7,
      "title": "Aga Khan Foundation International Scholarship",
      "description": "Provides scholarships on a 50% grant and 50% loan basis to outstanding students from developing countries for postgraduate studies.",
      "country": "International",
      "type": "NGO",
      "funding": "Partial",
      "deadline": "2025-03-31",
      "posted_date": "2025-03-28",
      "apply_link": "https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme",
      "tags": "AKF, Aga Khan, Masters, NGO, International",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "International",
      "level": "Masters",
      "host_organization": "Aga Khan Foundation"
    },
    {
      "id": 8,
      "title": "Punjab Educational Endowment Fund (PEEF)",
      "description": "Government of Punjab scholarship for matriculation and intermediate students from poor families in Punjab on merit-cum-need basis.",
      "country": "Pakistan",
      "type": "Government",
      "funding": "Partial",
      "deadline": "2025-07-01",
      "posted_date": "2025-04-09",
      "apply_link": "https://peef.org.pk/",
      "tags": "PEEF, Punjab, Matric, Intermediate, Need-based",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Punjab",
      "level": "Matric / Intermediate",
      "host_organization": "Government of Punjab"
    },
    {
      "id": 9,
      "title": "Australia Awards Scholarship 2025",
      "description": "Australian Government awards for Pakistani students to undertake full-time undergraduate or postgraduate study at Australian universities.",
      "country": "Australia",
      "type": "International",
      "funding": "Fully Funded",
      "deadline": "2025-04-30",
      "posted_date": "2025-04-03",
      "apply_link": "https://www.australiaawardspakistan.org/",
      "tags": "Australia, AAS, Masters, Undergraduate",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Australia",
      "level": "Undergraduate / Masters",
      "host_organization": "Australian Government"
    },
    {
      "id": 10,
      "title": "Sindh Government IT Scholarship 2025",
      "description": "Sindh IT Board offers technology scholarships for Sindh domicile students to pursue BS Computer Science, Software Engineering, or IT programs.",
      "country": "Pakistan",
      "type": "Government",
      "funding": "Fully Funded",
      "deadline": "2025-05-15",
      "posted_date": "2025-04-10",
      "apply_link": "https://stb.org.pk/",
      "tags": "Sindh, IT, CS, Software Engineering, Government",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Karachi / Hyderabad",
      "level": "Undergraduate",
      "host_organization": "Sindh Technical Board"
    }
  ],
  "Jobs": [
    {
      "id": 1,
      "title": "FPSC Assistant Director (BS-17) 2025",
      "description": "Federal Public Service Commission invites applications for Assistant Director posts in various federal ministries across Pakistan.",
      "category": "Government",
      "country": "Pakistan",
      "type": "Government",
      "deadline": "2025-05-20",
      "posted_date": "2025-04-10",
      "apply_link": "https://fpsc.gov.pk/",
      "tags": "FPSC, Government, BS-17, Federal",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Islamabad",
      "salary": "PKR 45,000 – 65,000/month",
      "experience": "Minimum 2 years"
    },
    {
      "id": 2,
      "title": "Software Engineer — Systems Limited",
      "description": "Systems Limited is hiring Software Engineers with expertise in React, Node.js, and cloud technologies for its Lahore development center.",
      "category": "IT / Technology",
      "country": "Pakistan",
      "type": "Private",
      "deadline": "2025-04-30",
      "posted_date": "2025-04-08",
      "apply_link": "https://www.systemsltd.com/careers",
      "tags": "Software Engineer, React, Node.js, IT, Private",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Lahore",
      "salary": "PKR 120,000 – 180,000/month",
      "experience": "1–3 years"
    },
    {
      "id": 3,
      "title": "PPSC Lecturer English (Female) 2025",
      "description": "Punjab Public Service Commission announces Lecturer posts in English for Government Higher Secondary Schools across Punjab (Female only).",
      "category": "Education",
      "country": "Pakistan",
      "type": "Government",
      "deadline": "2025-06-10",
      "posted_date": "2025-04-07",
      "apply_link": "https://ppsc.gop.pk/",
      "tags": "PPSC, Lecturer, English, Teacher, Punjab",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Punjab",
      "salary": "PKR 35,000 – 55,000/month",
      "experience": "Fresh / 1 year"
    },
    {
      "id": 4,
      "title": "Digital Marketing Manager — Daraz Pakistan",
      "description": "Daraz is looking for a skilled Digital Marketing Manager to lead SEO, SEM, and social media campaigns across its Pakistan platform.",
      "category": "Marketing",
      "country": "Pakistan",
      "type": "Private",
      "deadline": "2025-05-01",
      "posted_date": "2025-04-06",
      "apply_link": "https://careers.daraz.com/",
      "tags": "Daraz, Marketing, SEO, Social Media, Private",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Karachi",
      "salary": "PKR 100,000 – 150,000/month",
      "experience": "3–5 years"
    },
    {
      "id": 5,
      "title": "Junior Doctor — Shaukat Khanum Hospital",
      "description": "Shaukat Khanum Memorial Cancer Hospital & Research Centre requires Junior Doctors (House Officers) for its Lahore and Peshawar campuses.",
      "category": "Healthcare",
      "country": "Pakistan",
      "type": "Private",
      "deadline": "2025-04-25",
      "posted_date": "2025-04-05",
      "apply_link": "https://www.shaukatkhanum.org.pk/careers/",
      "tags": "Doctor, MBBS, Hospital, Healthcare, Medical",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Lahore / Peshawar",
      "salary": "PKR 80,000 – 120,000/month",
      "experience": "Fresh MBBS"
    },
    {
      "id": 6,
      "title": "Remote Freelance Content Writer (English)",
      "description": "International digital agency seeks Pakistan-based content writers for remote work. Writing blogs, articles, and social media content.",
      "category": "Media / Content",
      "country": "International",
      "type": "Remote",
      "deadline": "2025-12-31",
      "posted_date": "2025-04-09",
      "apply_link": "https://upwork.com",
      "tags": "Content Writer, Remote, Freelance, English, Work from Home",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Remote / Work from Home",
      "salary": "USD 300 – 800/month",
      "experience": "1 year"
    },
    {
      "id": 7,
      "title": "UN Women Programme Officer — Pakistan",
      "description": "UN Women Pakistan is recruiting a Programme Officer to support gender equality projects and women empowerment initiatives.",
      "category": "NGO / Development",
      "country": "Pakistan",
      "type": "NGO",
      "deadline": "2025-05-05",
      "posted_date": "2025-04-04",
      "apply_link": "https://www.unwomen.org/en/about-us/jobs",
      "tags": "UN Women, NGO, Gender, Development, United Nations",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Islamabad",
      "salary": "PKR 200,000 – 280,000/month",
      "experience": "3–5 years"
    },
    {
      "id": 8,
      "title": "NTS Junior Clerk (BPS-11) Sindh 2025",
      "description": "National Testing Service announces Junior Clerk positions for various Sindh government departments. Online application through NTS portal.",
      "category": "Government",
      "country": "Pakistan",
      "type": "Government",
      "deadline": "2025-05-15",
      "posted_date": "2025-04-03",
      "apply_link": "https://nts.org.pk/",
      "tags": "NTS, Clerk, BPS-11, Sindh, Government",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Sindh",
      "salary": "PKR 25,000 – 35,000/month",
      "experience": "Fresh / Matric"
    },
    {
      "id": 9,
      "title": "Data Analyst — Jazz Telecom Pakistan",
      "description": "Jazz is hiring Data Analysts to work with large datasets, create dashboards, and support business intelligence for the telecom sector.",
      "category": "IT / Technology",
      "country": "Pakistan",
      "type": "Private",
      "deadline": "2025-04-28",
      "posted_date": "2025-04-08",
      "apply_link": "https://jazz.com.pk/careers",
      "tags": "Jazz, Data Analyst, BI, SQL, Telecom",
      "is_featured": false,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Islamabad / Lahore",
      "salary": "PKR 90,000 – 140,000/month",
      "experience": "2–4 years"
    },
    {
      "id": 10,
      "title": "UNICEF Monitoring & Evaluation Officer",
      "description": "UNICEF Pakistan requires a Monitoring & Evaluation Officer to assess programme effectiveness in health and education sectors.",
      "category": "NGO / Development",
      "country": "Pakistan",
      "type": "NGO",
      "deadline": "2025-05-10",
      "posted_date": "2025-04-02",
      "apply_link": "https://www.unicef.org/careers/",
      "tags": "UNICEF, M&E, NGO, Health, Education",
      "is_featured": true,
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Lahore",
      "salary": "PKR 180,000 – 250,000/month",
      "experience": "3+ years"
    }
  ],
  "Internships": [
    {
      "id": 1,
      "title": "Web Development Intern — Arbisoft",
      "description": "Arbisoft offers a 3-month paid web development internship for CS/SE students. Work on real client projects using React and Django.",
      "organization": "Arbisoft",
      "country": "Pakistan",
      "stipend": "PKR 20,000/month",
      "deadline": "2025-05-01",
      "posted_date": "2025-04-10",
      "apply_link": "https://arbisoft.com/careers/",
      "tags": "Web Dev, React, Django, Internship, Lahore",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Lahore",
      "duration": "3 Months",
      "type": "Paid",
      "is_featured": true
    },
    {
      "id": 2,
      "title": "Marketing Intern — Unilever Pakistan",
      "description": "Unilever Pakistan's summer internship programme for marketing and business students. Gain corporate experience with global FMCG brand.",
      "organization": "Unilever Pakistan",
      "country": "Pakistan",
      "stipend": "PKR 25,000/month",
      "deadline": "2025-05-20",
      "posted_date": "2025-04-08",
      "apply_link": "https://www.unilever.com.pk/careers/",
      "tags": "Unilever, Marketing, FMCG, Summer Internship",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Karachi",
      "duration": "2 Months",
      "type": "Paid",
      "is_featured": true
    },
    {
      "id": 3,
      "title": "Research Intern — PIDE Islamabad",
      "description": "Pakistan Institute of Development Economics offers unpaid research internships for economics and social sciences students.",
      "organization": "PIDE",
      "country": "Pakistan",
      "stipend": "Unpaid",
      "deadline": "2025-06-01",
      "posted_date": "2025-04-07",
      "apply_link": "https://pide.org.pk/",
      "tags": "PIDE, Research, Economics, Islamabad, Unpaid",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Islamabad",
      "duration": "3 Months",
      "type": "Unpaid",
      "is_featured": false
    },
    {
      "id": 4,
      "title": "Graphic Design Intern — Media.net (Remote)",
      "description": "Media.net is seeking creative graphic design interns to work remotely. Create visuals for digital marketing campaigns.",
      "organization": "Media.net",
      "country": "International",
      "stipend": "USD 150/month",
      "deadline": "2025-05-15",
      "posted_date": "2025-04-06",
      "apply_link": "https://www.media.net/careers",
      "tags": "Graphic Design, Remote, Creative, Digital Media",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Remote",
      "duration": "2 Months",
      "type": "Paid",
      "is_featured": false
    },
    {
      "id": 5,
      "title": "HR Intern — Engro Corporation",
      "description": "Engro Corporation invites HR students for internship in human resources department. Learn talent acquisition and employee engagement.",
      "organization": "Engro Corporation",
      "country": "Pakistan",
      "stipend": "PKR 18,000/month",
      "deadline": "2025-04-30",
      "posted_date": "2025-04-05",
      "apply_link": "https://www.engro.com/careers",
      "tags": "Engro, HR, Human Resources, Internship, Karachi",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Karachi",
      "duration": "3 Months",
      "type": "Paid",
      "is_featured": false
    },
    {
      "id": 6,
      "title": "AI/ML Intern — NUST Research Lab",
      "description": "NUST Centre for Artificial Intelligence Research offers internships for engineering students interested in machine learning and AI projects.",
      "organization": "NUST CAIR",
      "country": "Pakistan",
      "stipend": "Unpaid",
      "deadline": "2025-07-01",
      "posted_date": "2025-04-04",
      "apply_link": "https://cair.nust.edu.pk/",
      "tags": "AI, ML, NUST, Research, Machine Learning",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Islamabad",
      "duration": "6 Months",
      "type": "Unpaid",
      "is_featured": true
    },
    {
      "id": 7,
      "title": "Finance Intern — HBL Bank Pakistan",
      "description": "Habib Bank Limited summer internship programme for finance and accounting students. Rotation across treasury, retail and corporate banking.",
      "organization": "HBL Pakistan",
      "country": "Pakistan",
      "stipend": "PKR 22,000/month",
      "deadline": "2025-05-10",
      "posted_date": "2025-04-03",
      "apply_link": "https://www.hbl.com/careers",
      "tags": "HBL, Bank, Finance, Internship, Summer",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Lahore / Karachi",
      "duration": "2 Months",
      "type": "Paid",
      "is_featured": false
    },
    {
      "id": 8,
      "title": "Social Media Intern — Dawn Media Group",
      "description": "Dawn Media Group offers social media and digital content internships for journalism and media students based in Karachi.",
      "organization": "Dawn Media",
      "country": "Pakistan",
      "stipend": "PKR 15,000/month",
      "deadline": "2025-05-25",
      "posted_date": "2025-04-02",
      "apply_link": "https://www.dawn.com/careers",
      "tags": "Dawn, Media, Social Media, Journalism, Karachi",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "location": "Karachi",
      "duration": "3 Months",
      "type": "Paid",
      "is_featured": false
    }
  ],
  "Exams": [
    {
      "id": 1,
      "title": "MDCAT 2025 — Medical & Dental College Admission Test",
      "exam_type": "MDCAT",
      "syllabus_link": "https://www.pmdc.org.pk/mdcat-syllabus",
      "test_date": "2025-09-14",
      "results_link": "https://www.pmdc.org.pk/mdcat-result",
      "past_papers_link": "https://www.pakprep.com/mdcat-past-papers",
      "fee": "PKR 3,500",
      "tags": "MDCAT, Medical, MBBS, BDS, Pakistan Medical Commission",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://www.pmdc.org.pk/registration",
      "eligibility": "FSc Pre-Medical (minimum 60%)",
      "conducting_body": "PMC (Pakistan Medical Commission)"
    },
    {
      "id": 2,
      "title": "CSS 2026 — Central Superior Services",
      "exam_type": "CSS",
      "syllabus_link": "https://www.fpsc.gov.pk/css-syllabus",
      "test_date": "2026-02-01",
      "results_link": "https://www.fpsc.gov.pk/css-result",
      "past_papers_link": "https://www.cssforum.com.pk/past-papers",
      "fee": "PKR 2,200",
      "tags": "CSS, Civil Services, FPSC, BPS-17, Competitive Exam",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://www.fpsc.gov.pk/css-apply",
      "eligibility": "Graduation (minimum 45%)",
      "conducting_body": "FPSC — Federal Public Service Commission"
    },
    {
      "id": 3,
      "title": "PPSC Punjab Public Service Commission 2025",
      "exam_type": "PPSC",
      "syllabus_link": "https://www.ppsc.gop.pk/syllabus",
      "test_date": "2025-07-20",
      "results_link": "https://www.ppsc.gop.pk/results",
      "past_papers_link": "https://www.ppsc.gop.pk/past-papers",
      "fee": "PKR 1,500",
      "tags": "PPSC, Punjab, Government Jobs, Lecturer, Tehsildar",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://www.ppsc.gop.pk/apply",
      "eligibility": "Graduation / Intermediate (varies by post)",
      "conducting_body": "PPSC — Punjab Public Service Commission"
    },
    {
      "id": 4,
      "title": "IELTS Academic 2025",
      "exam_type": "IELTS",
      "syllabus_link": "https://www.ielts.org/what-is-ielts/ielts-test-format",
      "test_date": "2025-05-17",
      "results_link": "https://www.ielts.org/results",
      "past_papers_link": "https://ieltsmaterial.com/ielts-past-papers",
      "fee": "PKR 39,500",
      "tags": "IELTS, English, British Council, IDP, Visa, Study Abroad",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://www.britishcouncil.pk/exam/ielts/book-test",
      "eligibility": "Matric / O-Levels (any)",
      "conducting_body": "British Council / IDP Education"
    },
    {
      "id": 5,
      "title": "NTS NAT 2025 — National Aptitude Test",
      "exam_type": "NTS",
      "syllabus_link": "https://nts.org.pk/nat-syllabus",
      "test_date": "2025-08-10",
      "results_link": "https://nts.org.pk/nat-result",
      "past_papers_link": "https://nts.org.pk/past-papers",
      "fee": "PKR 1,100",
      "tags": "NTS, NAT, Aptitude Test, Admission, University",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://nts.org.pk/nat-apply",
      "eligibility": "Intermediate / FA / FSc",
      "conducting_body": "NTS — National Testing Service"
    },
    {
      "id": 6,
      "title": "SAT 2025 — Scholastic Assessment Test",
      "exam_type": "SAT",
      "syllabus_link": "https://satsuite.collegeboard.org/sat/about-the-test",
      "test_date": "2025-05-03",
      "results_link": "https://satsuite.collegeboard.org/scores",
      "past_papers_link": "https://www.cracksat.net/sat-past-papers/",
      "fee": "USD 60",
      "tags": "SAT, USA, College Board, Undergraduate, US Scholarship",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://satsuite.collegeboard.org/sat/registration",
      "eligibility": "FSc / A-Levels (any)",
      "conducting_body": "College Board USA"
    },
    {
      "id": 7,
      "title": "GRE General Test 2025",
      "exam_type": "GRE",
      "syllabus_link": "https://www.ets.org/gre/revised_general/about/",
      "test_date": "2025-06-15",
      "results_link": "https://www.ets.org/gre/scores/",
      "past_papers_link": "https://www.gregmat.com/gre-past-papers",
      "fee": "USD 220",
      "tags": "GRE, Graduate, USA, Masters, PhD, ETS",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://www.ets.org/gre/revised_general/register/",
      "eligibility": "Graduation (any)",
      "conducting_body": "ETS — Educational Testing Service"
    },
    {
      "id": 8,
      "title": "FPSC Inspector Inland Revenue Test 2025",
      "exam_type": "FPSC",
      "syllabus_link": "https://fpsc.gov.pk/syllabus-ir",
      "test_date": "2025-06-05",
      "results_link": "https://fpsc.gov.pk/results",
      "past_papers_link": "https://cssforum.com.pk/fpsc-past-papers",
      "fee": "PKR 1,800",
      "tags": "FPSC, Inspector, Tax, FBR, Government, BS-16",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "registration_link": "https://fpsc.gov.pk/ir-apply",
      "eligibility": "Graduation in Commerce / Finance",
      "conducting_body": "FPSC — Federal Public Service Commission"
    }
  ],
  "Books": [
    {
      "id": 1,
      "title": "MDCAT Biology by Dr. Sajid Zafar",
      "category": "MDCAT Books",
      "exam_type": "MDCAT",
      "author": "Dr. Sajid Zafar",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "https://www.daraz.pk/products/mdcat-biology-sajid-zafar",
      "is_free": true,
      "tags": "MDCAT, Biology, Medical, Pakistan",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "2025 Edition",
      "language": "Urdu / English"
    },
    {
      "id": 2,
      "title": "Caravan CSS English Essay & Précis",
      "category": "CSS Books",
      "exam_type": "CSS",
      "author": "Caravan Book House",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "https://www.daraz.pk/products/caravan-css-english",
      "is_free": false,
      "tags": "CSS, English, Essay, Précis, FPSC",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "2024 Edition",
      "language": "English"
    },
    {
      "id": 3,
      "title": "PPSC Model Papers by Imtiaz Shahid",
      "category": "PPSC Books",
      "exam_type": "PPSC",
      "author": "Imtiaz Shahid",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "https://www.daraz.pk/products/ppsc-imtiaz-shahid",
      "is_free": false,
      "tags": "PPSC, Model Papers, Punjab, Government",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "2025 Edition",
      "language": "Urdu"
    },
    {
      "id": 4,
      "title": "Barron's IELTS Superpack",
      "category": "IELTS Books",
      "exam_type": "IELTS",
      "author": "Barron's Education Series",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "https://www.amazon.com/barrons-ielts",
      "is_free": false,
      "tags": "IELTS, English, British Council, Listening, Speaking",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "4th Edition",
      "language": "English"
    },
    {
      "id": 5,
      "title": "Official SAT Study Guide 2025",
      "category": "SAT Books",
      "exam_type": "SAT",
      "author": "College Board",
      "download_link": "https://satsuite.collegeboard.org/media/pdf/official-sat-study-guide-2025.pdf",
      "buy_link": "https://www.amazon.com/official-sat-study-guide",
      "is_free": true,
      "tags": "SAT, College Board, USA, Official",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "2025 Edition",
      "language": "English"
    },
    {
      "id": 6,
      "title": "GRE Official Guide by ETS",
      "category": "GRE Books",
      "exam_type": "GRE",
      "author": "Educational Testing Service",
      "download_link": "https://www.ets.org/gre/revised_general/prepare/official_test_prep/",
      "buy_link": "https://www.amazon.com/gre-official-guide",
      "is_free": true,
      "tags": "GRE, ETS, Verbal, Quantitative, Official",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "3rd Edition",
      "language": "English"
    },
    {
      "id": 7,
      "title": "Gray's Anatomy for Students",
      "category": "Medical Books",
      "exam_type": "MDCAT / MBBS",
      "author": "Richard Drake",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "https://www.daraz.pk/products/grays-anatomy-students",
      "is_free": false,
      "tags": "Anatomy, Medical, MBBS, Gray's, First Year",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "4th Edition",
      "language": "English"
    },
    {
      "id": 8,
      "title": "MDCAT Chemistry Notes by Punjab Board",
      "category": "MDCAT Books",
      "exam_type": "MDCAT",
      "author": "Punjab Textbook Board",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "",
      "is_free": true,
      "tags": "MDCAT, Chemistry, Punjab Board, Free Notes",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "2025 Edition",
      "language": "Urdu / English"
    },
    {
      "id": 9,
      "title": "NTS Complete Guide by Ch. Ahmed Najib",
      "category": "NTS Books",
      "exam_type": "NTS",
      "author": "Ch. Ahmed Najib",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "https://www.daraz.pk/products/nts-ahmed-najib",
      "is_free": false,
      "tags": "NTS, NAT, Aptitude, General Knowledge",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "2024 Edition",
      "language": "Urdu"
    },
    {
      "id": 10,
      "title": "CSS Current Affairs — Jahangir World Times",
      "category": "CSS Books",
      "exam_type": "CSS",
      "author": "Jahangir World Times",
      "download_link": "https://drive.google.com/uc?id=REPLACE_WITH_FREE_PDF_ID",
      "buy_link": "https://www.daraz.pk/products/jwt-current-affairs",
      "is_free": false,
      "tags": "CSS, Current Affairs, Pakistan Affairs, JWT",
      "image_url": "https://drive.google.com/uc?id=REPLACE_WITH_YOUR_IMAGE_ID",
      "edition": "2025 Edition",
      "language": "English"
    }
  ],
  "Notifications": [
    {
      "id": 1,
      "message": "🔴 URGENT: Chevening Scholarship 2025 deadline is November 5 — Apply Now!",
      "type": "urgent",
      "expiry_date": "2025-11-05",
      "is_active": true,
      "link": "https://www.chevening.org/apply/"
    },
    {
      "id": 2,
      "message": "📢 HEC Need-Based Scholarships open — Last date June 30, 2025",
      "type": "scholarship",
      "expiry_date": "2025-06-30",
      "is_active": true,
      "link": "https://hec.gov.pk/scholarships"
    },
    {
      "id": 3,
      "message": "💼 FPSC Assistant Director (BS-17) applications closing May 20",
      "type": "job",
      "expiry_date": "2025-05-20",
      "is_active": true,
      "link": "https://fpsc.gov.pk/"
    },
    {
      "id": 4,
      "message": "📚 MDCAT 2025 registration starts July 2025 — Prepare now!",
      "type": "exam",
      "expiry_date": "2025-09-01",
      "is_active": true,
      "link": "https://www.pmdc.org.pk/registration"
    },
    {
      "id": 5,
      "message": "🎓 Australia Awards Scholarship 2025 — Deadline April 30",
      "type": "scholarship",
      "expiry_date": "2025-04-30",
      "is_active": true,
      "link": "https://www.australiaawardspakistan.org/"
    },
    {
      "id": 6,
      "message": "💡 New CSS books added — Download free PDF study material",
      "type": "book",
      "expiry_date": "2025-12-31",
      "is_active": true,
      "link": "https://careerhub.pk/books.html"
    },
    {
      "id": 7,
      "message": "🚀 Arbisoft Web Dev Internship — Apply before May 1",
      "type": "internship",
      "expiry_date": "2025-05-01",
      "is_active": true,
      "link": "https://arbisoft.com/careers/"
    },
    {
      "id": 8,
      "message": "📝 PPSC Lecturer posts announced — Punjab domicile holders apply",
      "type": "job",
      "expiry_date": "2025-06-10",
      "is_active": true,
      "link": "https://ppsc.gop.pk/"
    },
    {
      "id": 9,
      "message": "🌍 DAAD Germany Scholarship 2025 — Deadline August 20",
      "type": "scholarship",
      "expiry_date": "2025-08-20",
      "is_active": true,
      "link": "https://www.daad.de/en/"
    },
    {
      "id": 10,
      "message": "🏥 MDCAT 2025 exam date confirmed: September 14",
      "type": "exam",
      "expiry_date": "2025-09-14",
      "is_active": true,
      "link": "https://www.pmdc.org.pk/"
    }
  ]
};
